name: mcbe_addon_merger
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 0.0.1-alpha1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  file_picker: ^4.3.1
  google_fonts: ^2.3.3
  json_annotation: ^4.4.0
  json_patch: ^3.0.0
  logger: ^1.1.0
  numerus: ^2.0.0
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.0
  flutter_lints: ^1.0.0
  json_serializable: ^6.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
